services:
  router_a:
    build: .
    container_name: gobgp_1
    command: ["gobgpd", "-f", "/etc/gobgp/gobgp.conf"]
    environment:
      - GOBGP_OPERA_ENABLED=true
    volumes:
      - ./conf1.conf:/etc/gobgp/gobgp.conf
    networks:
      labnet:
        ipv4_address: 10.0.0.2

  router_b:
    build: .
    container_name: gobgp_2
    command: ["gobgpd", "-f", "/etc/gobgp/gobgp.conf"]
    environment:
      - GOBGP_OPERA_ENABLED=true
    volumes:
      - ./conf2.conf:/etc/gobgp/gobgp.conf
    networks:
      labnet:
        ipv4_address: 10.0.0.3

  router_c:
    build: .
    container_name: gobgp_3
    command: ["gobgpd", "-f", "/etc/gobgp/gobgp.conf"]
    environment:
      - GOBGP_OPERA_ENABLED=true
    volumes:
      - ./conf3.conf:/etc/gobgp/gobgp.conf
    networks:
      labnet:
        ipv4_address: 10.0.0.4

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
