[project]
name = "gobgp"
version = "0.1.0"
description = "A IP address resolver for gobgp"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "uvicorn>=0.35.0",
    "requests>=2.32.5"
]
