image:
  repository: gobgp
  tag: dev
  pullPolicy: IfNotPresent

routers:
  router-a:
    asn: 65001
    routerId: 1.1.1.1
    neighbors:
      - name: router-b
        peerAs: 65002
        communitiesAddTags: [100]
      - name: router-c
        peerAs: 65003
        communitiesAddTags: [200]

  router-b:
    asn: 65002
    routerId: 2.2.2.2
    neighbors:
      - name: router-a
        peerAs: 65001
        communitiesAddTags: [100]
      - name: router-d
        peerAs: 65004
        communitiesAddTags: [100]

  router-c:
    asn: 65003
    routerId: 3.3.3.3
    neighbors:
      - name: router-a
        peerAs: 65001
        communitiesAddTags: [200]
      - name: router-d
        peerAs: 65004
        communitiesAddTags: [200]

  router-d:
    asn: 65004
    routerId: 4.4.4.4
    neighbors:
      - name: router-b
        peerAs: 65002
        communitiesAddTags: [100]
      - name: router-c
        peerAs: 65003
        communitiesAddTags: [200]
